- name: Konfiguracja serwera WWW
  hosts: web
  become: yes
  tasks:
    - name: Aktualizacja apt i instalacja Python 3
      apt:
        name: 
          - python3
          - python3-pip
          - nginx
        state: present
        update_cache: yes

    - name: Tworzenie pliku index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Strona działa!</h1>"
      notify:
        - restart nginx

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted

        fi
      args:
        warn: false
